version: '3'

services:
  traefik:
    image: traefik:1.7
    command:
      - --docker
      - --api
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  app_staging:
    image: registry.gitlab.com/108kb/my-awesome-project:staging
    labels:
      - "traefik.port=3000"
      - "traefik.frontend.rule=Host:app-staging.evilfactory.id"
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - IS_STAGING=true

  app:
    image: registry.gitlab.com/108kb/my-awesome-project:stable
    labels:
      - "traefik.port=3000"
      - "traefik.frontend.rule=Host:app.evilfactory.id"
    environment:
      - HOST=0.0.0.0
      - PORT=3000
